language: cpp
compiler:
  - gcc
  
  
before_install:
 - mkdir auto_install
 - cd auto_install
 - git clone git@github.com:lengagne/mogs_tinyxml.git
 - cd mogs_tinyxml
 - sudo ./install_packages_ubuntu.sh
 - mkdir build; cd build
 - cmake -DCMAKE_BUILD_TYPE=Release .. ; make ; sudo make install 
 - cd ../..
 - sudo ./install_packages_ubuntu.sh

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
